############ WEBSERV WEBSERVER SETTINGS ############
default['WEBSERV']['PsCfgHome'] = '/apps/psoft/pt854'
default['WEBSERV']['UserId'] = 'system'
default['WEBSERV']['UserPwd'] = 'password11'
default['WEBSERV']['DomainName'] = 'tpapsappd2_fin_example'
default['WEBSERV']['BEA_HOME'] = '/apps/psoft/weblogic1212'
default['WEBSERV']['SingleOrMultiIntall'] = 'SINGLE'
default['WEBSERV']['WebSiteName'] = 'FIUDEV'
default['WEBSERV']['AppServerName'] = 'nycfindtst1.timeinc.com'
default['WEBSERV']['JSLPort'] = '9200'
default['WEBSERV']['HTTPPort'] = '4080'
default['WEBSERV']['HTTPSPort'] = '443'
default['WEBSERV']['AuthDomain'] = 'timeinc.com'
default['WEBSERV']['WebProfName'] = 'DEV'
default['WEBSERV']['WebProfPwd'] = 'asdf11asdf'
default['WEBSERV']['IGWUserId'] = 'administrator'
default['WEBSERV']['IGWPwd'] = 'password'
default['WEBSERV']['ReportsDir'] = '/appdata/psreports'
default['WEBSERV']['PSHome'] = '/apps/psoft/pt854'
default['WEBSERV']['PIAHome'] = '/apps/psoft/pt854'
default['WEBSERV']['WLHome'] = '/apps/psoft/weblogic1212/wlserver'
default['WEBSERV']['JavaOptionsLinux'] = '-server -Xms1536m -Xmx1536m -XX:MaxPermSize=256m -Dtoplink.xml.platform=oracle.toplink.platform.xml.jaxp.JAXPPlatform -Dcom.sun.xml.namespace.QName.useCompatibleSerialVersionUID=1.0'
default['WEBSERV']['AdmHostName'] = 'tpapsappp1.timeinc.com'
default['WEBSERV']['AdmServerName'] = 'WebLogicAdmin'
